apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: <aws_account_id>.dkr.ecr.us-east-1.amazonaws.com/appointment-service:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
